library:
  source-dirs: src
tests:
  haskell-insta-webscraper-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-insta-webscraper
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
- scalpel
- base >= 4.7 && < 5
name: haskell-insta-webscraper
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/haskell-insta-webscraper
license: BSD3
executables:
  haskell-insta-webscraper-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-insta-webscraper
description: Please see the README on GitHub at <https://github.com/githubuser/haskell-insta-webscraper#readme>
